name: Review application

on:
  issues:
    types: [opened, edited]

jobs:
  review-application:
    runs-on: ubuntu-latest
    if: vars.PROCESSOR_ENABLED == 'true' && contains(github.event.issue.labels.*.name, 'application')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch processor
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          file: "processor"
          target: "./processor"

      - name: Automated application review
        run: |
          chmod +x ./processor
          ./processor review
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          OP_BOT_PAT: ${{ secrets.OP_BOT_PAT }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
